
GET http://localhost:8080/api/auth/user/profile

###
GET http://localhost:8080/api/auth/admin

###
POST http://localhost:8080/api/auth/user/profile/contact
credentials: "include"
Content-Type: application/json

{
        "message": "test"
}